name_or_path: gpt2
name: gpt-2
model_vec_size: 3840
class_name: AutoModelForCausalLM
edit_modules:
# - transformer.h.1.mlp.c_proj
# - transformer.h.2.mlp.c_proj
# - transformer.h.3.mlp.c_proj
# - transformer.h.4.mlp.c_proj
# - transformer.h.5.mlp.c_proj
- transformer.h.6.mlp.c_proj
- transformer.h.7.mlp.c_proj
- transformer.h.8.mlp.c_proj
- transformer.h.9.mlp.c_proj
- transformer.h.10.mlp.c_proj
- transformer.h.11.mlp.c_proj
# - transformer.h.6.mlp.c_fc
# - transformer.h.7.mlp.c_fc
# - transformer.h.8.mlp.c_fc
# - transformer.h.9.mlp.c_fc
# - transformer.h.10.mlp.c_fc
# - transformer.h.11.mlp.c_fc
half: False