name_or_path: ${oc.env:PWD}/models/Llama-3.2-1B-eos-sft-template-format-curated-v1-lr2e-6-sample-10
name: llama-3.2-base-qa
# model_vec_size: 18432
class_name: AutoModelForCausalLM
edit_modules:
# ###############################
- model.layers.4.mlp.gate_proj
- model.layers.5.mlp.gate_proj
- model.layers.6.mlp.gate_proj
- model.layers.7.mlp.gate_proj
- model.layers.8.mlp.gate_proj
- model.layers.9.mlp.gate_proj
- model.layers.10.mlp.gate_proj
- model.layers.11.mlp.gate_proj
- model.layers.12.mlp.gate_proj
- model.layers.13.mlp.gate_proj
- model.layers.14.mlp.gate_proj
- model.layers.15.mlp.gate_proj
# - model.layers.31.mlp.gate_proj
###############################
- model.layers.4.mlp.up_proj
- model.layers.5.mlp.up_proj
- model.layers.6.mlp.up_proj
- model.layers.7.mlp.up_proj
- model.layers.8.mlp.up_proj
- model.layers.9.mlp.up_proj
- model.layers.10.mlp.up_proj
- model.layers.11.mlp.up_proj
- model.layers.12.mlp.up_proj
- model.layers.13.mlp.up_proj
- model.layers.14.mlp.up_proj
- model.layers.15.mlp.up_proj
# - model.layers.31.mlp.up_proj
###############################
- model.layers.4.mlp.down_proj
- model.layers.5.mlp.down_proj
- model.layers.6.mlp.down_proj
- model.layers.7.mlp.down_proj
- model.layers.8.mlp.down_proj
- model.layers.9.mlp.down_proj
- model.layers.10.mlp.down_proj
- model.layers.11.mlp.down_proj
- model.layers.12.mlp.down_proj
- model.layers.13.mlp.down_proj
- model.layers.14.mlp.down_proj
- model.layers.15.mlp.down_proj

half: True