name: newmalmen
rank: 1920
n_blocks: 8
lr: 1e-6
meta_lr: 1e-7
loc_coef: 1
max_grad_norm: 1
n_epochs: 6
batch_size: 512
token: ans
cache_dir: cache
cache_dir_2: /root/autodl-tmp/cache
save_checkpoint: False
load_checkpoint: False
hidden_size: 1024
n_gru: 2
n_test: 10
reg_coef: 1e-2